# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_login', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('commission', models.FloatField()),
                ('cashback', models.FloatField()),
                ('referral', models.FloatField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='click',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Offer'),
        ),
        migrations.AddField(
            model_name='click',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.Customer'),
        ),
    ]
