# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0003_company_logo'),
        ('main', '0003_auto_20170522_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='mailed',
            field=models.IntegerField(default=1),
        ),
    ]
