# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170529_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='mailed',
            field=models.IntegerField(default=0),
        ),
    ]
