# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170529_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='category',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
