# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170704_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='hot',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 7, 19, 49, 34, 338420, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 7, 19, 49, 34, 338420, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 7, 19, 49, 34, 338420, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 7, 19, 49, 34, 338420, tzinfo=utc), null=True),
        ),
    ]
