# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170529_1949'),
        ('user_login', '0003_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='categories',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
