# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0004_customer_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='categories',
            new_name='category',
        ),
    ]
