# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0005_auto_20170529_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referee_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
