# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0007_auto_20170618_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 18, 13, 4, 37, 797489, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 18, 13, 4, 37, 797489, tzinfo=utc), null=True),
        ),
    ]
