# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0009_auto_20170703_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ifsc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='paytm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='paytm_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 4, 18, 18, 59, 125199, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 4, 18, 18, 59, 125199, tzinfo=utc), null=True),
        ),
    ]
