# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0011_auto_20170708_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 10, 13, 7, 703674, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 8, 10, 13, 7, 703674, tzinfo=utc), null=True),
        ),
    ]
