# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0012_auto_20170708_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 19, 17, 7, 51, 429654, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 19, 17, 7, 51, 429654, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
